---

# - hosts: database
#   become: yes
#   vars_files:
#     - host_vars/remote_vars.yaml
#   gather_facts: true
#   roles:
#     # - role: delete-containers
#     - role: deploy-couchdb
#     - role: clone-git-sourcefile
#     - role: deploy-new-loader
#     - role: deploy-backend

# - hosts: instance2
#   become: yes
#   vars_files:
#     - host_vars/remote_vars.yaml
#   gather_facts: true
#   roles:
#     - role: deploy-crawler

- hosts: instance4
  become: yes
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: delete-containers
    - role: clone-git-sourcefile
    - role: deploy-frontend
    - role: deploy-nginx

# - hosts: instance2
#   become: yes
#   vars_files:
#     - host_vars/remote_vars.yaml
#   gather_facts: true
#   roles:
#     - role: clone-git-sourcefile
#     - role: deploy-backend