---
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - host_vars/local_vars.yaml
    - host_vars/remote_vars.yaml
  gather_facts: true

  roles:
    - role: common
    - role: show-images
    - role: create-volumes
    - role: create-security-groups
    - role: create-instances