---
- hosts: all
  vars_files:
    - host_vars/local_vars.yaml
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: install-environments
    - role: clone-git-sourcefile
    - role: setup-docker