# - name: conf nginx.conf file
#   become: yes
#   lineinfile: 
#     path: /home/connor/test-ansible/roles/deploy-nginx/nginx.conf
#     insertbefore: "        #upstream backendserver input here"
#     line: "        server {{groups['masternode'][0]}}:6100;\n        server {{groups['workers'][0]}}:6100;\n        server {{groups['workers'][0]}}:6100;"


# - name: conf nginx.conf file
#   become: yes
#   lineinfile: 
#     path: /home/connor/test-ansible/roles/deploy-nginx/nginx.conf
#     insertbefore: "            # proxy_pass input here"
#     line: "            proxy_pass   http://{{groups['instance4'][0]}}:3000;"
  
- name: delete defaul nginx conf file from the server
  become: yes
  file:
    path: /etc/nginx/nginx.conf
    state: absent

- name: upload nginx conf to server
  become: yes
  template:
    src: nginx.conf.j2
    dest: '/etc/nginx/nginx.conf'
    owner: ubuntu
    group: ubuntu


- name: restart the nginx service
  become: yes
  shell: sudo service nginx start