---
- name: build docker image for flask app 
  command: docker build -t flaskapp:latest .
  args:
    chdir: '{{remote_working_directory}}/backend'

- name: sleep for three seconds
  command: sleep 3

- name: run docker image 
  command: docker run -it -d --name flaskapp --net host flaskapp
  when: ansible_host == groups['workers'][0]

- name: sleep for three seconds
  command: sleep 3

- name: run docker image 
  command: docker run -it -d --name flaskapp --net host flaskapp
  when: ansible_host == groups['workers'][1]

- name: sleep for three seconds
  command: sleep 3
  
- name: run docker image 
  command: docker run -it -d --name flaskapp --net host flaskapp
  when: ansible_host == groups['masternode'][0]

- name: sleep for three seconds
  command: sleep 3

- name: restart docker container 
  command: docker restart flaskapp